dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [
    path('admin-site/', admin.site.urls),
    path('admin/',include('davur.urls', namespace='davur')),
    path('',include('frontend.urls', namespace='frontend')),
    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),
    
]
if settings.DEBUG == True or settings.DEBUG == False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header  =  "Davur Dashboard"  
admin.site.site_title  =  "Dashboard"
admin.site.index_title  =  "Dashboard"

davur/urls.py
from django.urls import path
from davur import davur_views
from users import users_views
app_name='davur'
urlpatterns = [

	path('users/',users_views.users,name="users"),
	path('user-details/<int:id>/',users_views.user_details,name="user-details"),
	path('add-user/',users_views.add_user,name="add-user"),
	path('edit-user/<int:id>/',users_views.edit_user,name="edit-user"),
	path('delete-user/<int:id>/',users_views.delete_user,name="delete-user"),
	path('delete-multiple-user/',users_views.delete_multiple_user,name="delete-multiple-user"),

	path('login/',users_views.login_user,name="login"),
	path('logout/',users_views.logout_user,name="logout"),
	path('groups/',users_views.groups_list,name="groups"),
	path('group-edit/<int:id>/',users_views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',users_views.group_delete,name="group-delete"),
	path('group-add/',users_views.group_add,name="group-add"),
	path('permissions/',users_views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',users_views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',users_views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',users_views.assign_permissions_to_user,name="assign-permissions-to-user"),
	# path('signup/',users_views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',users_views.activate, name='activate'),



















    path('',davur_views.index,name="index"),
    path('index/',davur_views.index,name="index"),
    path('page-analytics/',davur_views.page_analytics,name="page-analytics"),
    path('page-review/',davur_views.page_review,name="page-review"),
    path('page-order/',davur_views.page_order,name="page-order"),
    path('page-order-list/',davur_views.page_order_list,name="page-order-list"),
    path('page-general-customers/',davur_views.page_general_customers,name="page-general-customers"),
    path('app-profile/',davur_views.app_profile,name="app-profile"),
    path('post-details/',davur_views.post_details,name="post-details"),
    path('email-compose/',davur_views.email_compose,name="email-compose"),
    path('email-inbox/',davur_views.email_inbox,name="email-inbox"),
    path('email-read/',davur_views.email_read,name="email-read"),
    path('app-calender/',davur_views.app_calender,name="app-calender"),
    path('ecom-product-grid/',davur_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',davur_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',davur_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',davur_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',davur_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',davur_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',davur_views.ecom_customers,name="ecom-customers"),
    path('chart-flot/',davur_views.chart_flot,name="chart-flot"),
    path('chart-morris/',davur_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',davur_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',davur_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',davur_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',davur_views.chart_peity,name="chart-peity"),
    path('ui-accordion/',davur_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',davur_views.ui_alert,name="ui-alert"),
    path('ui-badge/',davur_views.ui_badge,name="ui-badge"),
    path('ui-button/',davur_views.ui_button,name="ui-button"),
    path('ui-modal/',davur_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',davur_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',davur_views.ui_list_group,name="ui-list-group"),
    path('ui-media-object/',davur_views.ui_media_object,name="ui-media-object"),
    path('ui-card/',davur_views.ui_card,name="ui-card"),
    path('ui-carousel/',davur_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',davur_views.ui_dropdown,name="ui-dropdown"),
    path('ui-popover/',davur_views.ui_popover,name="ui-popover"),
    path('ui-progressbar/',davur_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',davur_views.ui_tab,name="ui-tab"),
    path('ui-typography/',davur_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',davur_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',davur_views.ui_grid,name="ui-grid"),
    path('uc-select2/',davur_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',davur_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',davur_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',davur_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',davur_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',davur_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',davur_views.uc_lightgallery,name="uc-lightgallery"),
    path('widget-basic/',davur_views.widget_basic,name="widget-basic"),
    path('form-element/',davur_views.form_element,name="form-element"),
    path('form-wizard/',davur_views.form_wizard,name="form-wizard"),
    path('form-ckeditor/',davur_views.form_ckeditor,name="form-ckeditor"),
    path('form-pickers/',davur_views.form_pickers,name="form-pickers"),
    path('form-validation-jquery/',davur_views.form_validation_jquery,name="form-validation-jquery"),
    path('table-bootstrap-basic/',davur_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',davur_views.table_datatable_basic,name="table-datatable-basic"),
    path('page-error-400/',davur_views.page_error_400,name="page-error-400"),
    path('page-error-403/',davur_views.page_error_403,name="page-error-403"),
    path('page-error-404/',davur_views.page_error_404,name="page-error-404"),
    path('page-error-500/',davur_views.page_error_500,name="page-error-500"),
    path('page-error-503/',davur_views.page_error_503,name="page-error-503"),

    path('page-lock-screen/',davur_views.page_lock_screen,name="page-lock-screen"),

    
]

davur/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager 
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group




class CustomAccountManager(BaseUserManager):

	def create_superuser(self, email, first_name, last_name, password,**other_fields):
		other_fields.setdefault('is_staff',True)
		other_fields.setdefault('is_superuser',True)
		other_fields.setdefault('is_active',True)

		if other_fields.get('is_staff') is not True:
			raise ValueError(
				'Superuser must be assigned to is_staff=True.')
		if other_fields.get('is_superuser') is not True:
			raise ValueError(
				'Superuser must be assigned to is_superuser=True.')


		super_user = self.create_user(email,first_name, last_name, password, **other_fields)

		return super_user


	def create_user(self, email, first_name, last_name, password,**other_fields):
		# email validation
		if not email:
			raise ValueError(_('You must provide an email address'))

		email = self.normalize_email(email)
		user = self.model(email=email, first_name=first_name, last_name=last_name, **other_fields)
		user.set_password(password)
		user.save()
		return user


def user_directory_path(instance, filename):
	# file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
	return f'{instance.email}/{filename}'

#This is the new custom user model
class CustomUser(AbstractBaseUser, PermissionsMixin):
	GENDER_CHOICES = (
		('','Choose gender'),
		('Male', 'Male'),
		('Female', 'Female'),
		('Others', 'Others'),
	)
	email = models.EmailField(_('email address'),unique=True)
	first_name = models.CharField(max_length=150,blank=True)
	last_name = models.CharField(max_length=150,blank=True)
	gender = models.CharField(max_length=100, choices=GENDER_CHOICES,blank=True)
	avatar = models.ImageField(upload_to=user_directory_path, default="profile/image/default.gif")
	dob = models.CharField(max_length=150,blank=True,null=True,help_text="Pattern = dd-mm-yyyy")
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)# Validators should be a list
	groups = models.ManyToManyField(Group,blank=True)
	about = models.TextField(_('about'),max_length=500,blank=True)
	is_staff = models.BooleanField(default=False)
	is_active = models.BooleanField(default=False)# this false work on ui not in admin
	#when user is created, than system send a email after varify  user is active

	objects = CustomAccountManager()

	USERNAME_FIELD = 'email'  
	REQUIRED_FIELDS = ['first_name','last_name']

	def __str__(self):
		return f"{self.first_name} {self.last_name}"

users/forms.py
from django import forms
from users.models import CustomUser
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = ('email',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2',
                )
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


#Add User Form
class CustomUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    dob = forms.CharField(required=True)
    phone_number = forms.CharField(required=True)
    
    GENDER_CHOICES = (
        ('','Choose gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, required=True)


    class Meta:
        model = CustomUser
        fields = ('email',
                  'first_name',
                  'last_name',
                  'gender',
                  'avatar',
                  'dob',
                  'phone_number',
                  'groups',
                  'about',
                  'is_active',
                  'password1',
                  'password2',
                )
        widgets = {
            'avatar': forms.FileInput(),
        }
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    dob = forms.CharField(required=True)
    phone_number = forms.CharField(required=True)

    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)
   
    GENDER_CHOICES = (
        ('','Choose gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICES, required=True)

    class Meta:
        model = CustomUser
        fields = ('email',
                  'first_name',
                  'last_name',
                  'gender',
                  'avatar',
                  'dob',
                  'phone_number',
                  'groups',
                  'about',
                  'is_active',
                )

        widgets = {
            'avatar': forms.FileInput(),
        }

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save()
        return user




class LoginForm(forms.Form):
    email =  forms.EmailField()
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data
        
    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user
        

class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not CustomUser.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no user registered with the specified email address!")
        return email


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name','permissions')

class PermissionsForm(forms.ModelForm):
    name = forms.CharField(label='Name', help_text="Example: Can action modelname")
    codename = forms.CharField(label='Code Name', help_text="Example: action_modelname")

    class Meta:
        model = Permission
        fields = ('name','codename','content_type')


class UserPermissionsForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('user_permissions',)




davur/views.py
from django.shortcuts import render

# Create your views here.

templates/davur/modules/add-permissions.html
{% extends 'davur/elements/layouts/admin.html' %}
{% load static widget_tweaks %}


{% block additional_css %}

{% endblock %}

{% block message %}
{% include 'davur/elements/alert.html' %}
{% endblock %}

{% block content %}




<div class="row justify-content-center h-100 align-items-center">
<div class="col-xl-12 col-lg-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Add New Permissions</h4>

        </div>


        <div class="card-body">
            <div class="basic-form">
                <form  method="post" enctype="multipart/form-data" autocomplete="off">{% csrf_token %}
                    <div class="row">
                            <div class="mb-3 col-md-12">
                                <label class="form-label">Name</label>
                                {{ form.name|attr:"type:text"|attr:"class:form-control"}}
                                <span class="text-muted fs-12">{{ form.name.help_text }}</span>
                            </div>

                            <div class="mb-3 col-md-12">
                                <label class="form-label">Code Name</label>
                                {{ form.codename|attr:"type:text"|attr:"class:form-control"}}
                                <span class="text-muted fs-12">{{ form.codename.help_text }}</span>
                            </div>

                            <div class="mb-3 col-md-12">
                                    
                                <label class="form-label">Content Type</label>
                                {{ form.content_type|attr:"type:text"|attr:"class:default-select form-control wide"}}
                                
                            </div>
                        
                        
                    </div>

                    <button type="submit" class="btn btn-secondary">Save</button>
                    <a href="{% url 'davur:index' %}" class="btn btn-primary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
    
</div>
</div> 

  
{% endblock %}


{% block additional_js %}
{% endblock %}



templates/davur/modules/users.html
{% extends 'davur/elements/layouts/admin.html' %}
{% load static %}


{% block additional_css %}
 
{% endblock %}



{% block message %}
{% include 'davur/elements/alert.html' %}
{% endblock %}


{% block content %}

<div id="message">
</div>     
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header flex-wrap">
                    <h4 class="card-title mb-2">Users Table</h4>
                    
                    <div class="d-flex mb-2">

                        {% if perms.users.delete_customuser %}
                       
                        <button type="submit" id="delete_multiple_btn" class="btn light btn-outline-primary btn-sm me-2 ">Delete</button>
                        
                        {% endif %}

                        {% if perms.users.add_customuser %}
                        <a href="{% url 'davur:add-user' %}" class="btn btn-primary btn-sm ">ADD USER  <span class="btn-icon-end">
                            <i class="fa fa-plus"></i></span>
                        </a>
                        {% endif %}

                    </div>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-responsive-md">
                            <thead>
                                <tr>
                                    <th style="width:50px;">
                                        <div class="form-check custom-checkbox checkbox-primary check-lg me-3">
                                            <input  type="checkbox" class="form-check-input" id="checkAll" value="">
                                            <label class="form-check-label" for="checkAll"></label>
                                        </div>
                                    </th>
                                   
                                    <th>Full Name</th>
                                    <th>Email</th>
                                    <th>Gender</th>
                                    <th>Groups</th>
                                    <th>Mobile</th>
                                    <th>Date of Birth</th>
                                    <th>Status</th>


                                    {% if perms.users.delete_customuser or perms.users.change_customuser or perms.auth.change_permission %}
                                    <th></th>
                                    {% endif %}


                                   
                                </tr>
                            </thead>
                            <tbody>
                                {% csrf_token %}
                                {% for user in user_list %}
                                <tr id="{{ user.id }}">
                                    <td>
                                        <div class="form-check custom-checkbox checkbox-primary check-lg me-3">
                                            <input name="user_id[]" type="checkbox" class="form-check-input" value="{{ user.id }}">
                                            <label class="form-check-label" for="checkbox-{{ user.id }}"></label>
                                        </div>
                                    </td>


                                    <td>
                                        <a href="{% url 'davur:user-details' id=user.id %}">
                                        <div class="d-flex align-items-center">
                                            <img src="/media/{{ user.avatar }}" class="rounded-lg me-2" width="24" alt=""> 
                                            <span class="w-space-no">{{ user.first_name }} {{ user.last_name }}</span>
                                        </div>
                                    </a>
                                    </td>
                                    <td><strong>{{ user.email }}</strong></td>
                                    <td>{{ user.gender }}</td>
                                    
                                   
                                    <td>	
                                        {% for g in user.groups.all %}
                                        <span class="badge  badge-xs badge-primary light">{{ g.name }}</span>
                                        {% endfor %}
                                    </td>
                                    <td>{{ user.phone_number }}</td>
                                    <td>{{ user.dob }}</td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            {% if user.is_active %}
                                            <i class="fa fa-circle text-success me-1"></i> 
                                            {% else %} 
                                            <i class="fa fa-circle text-dark me-1"></i> 

                                            {% endif %}
                                        </div>
                                    
                                    </td>
                                    <td>
                                        <div class="sweetalert">
                                            <div class="d-flex">
                                                {% if perms.auth.change_permission %}
                                                <a href="{% url 'davur:assign-permissions-to-user' id=user.id %}" class="btn btn-success shadow btn-xs sharp me-1"><i class="fa fa-shield-alt"></i></a>
                                                {% endif %}
                                                {% if perms.users.change_customuser %}
                                                <a href="{% url 'davur:edit-user' id=user.id %}" class="btn btn-primary shadow btn-xs sharp me-1"><i class="fa fa-pencil-alt"></i></a>
                                                {% endif %}
                                                {% if perms.users.delete_customuser %}
                                                <a href="{% url 'davur:delete-user' id=user.id %}" class="btn btn-danger shadow btn-xs sharp sweet-success-cancel"><i class="fa fa-trash"></i></a>
                                                {% endif %}
                                            </div>
                                    </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>


                    <nav mt-5>

                        <p>
                            <span class="current">
                            Page {{ user_list.number }} of {{ user_list.paginator.num_pages }}.
                           </span> 
                           </p>
                           

                        <ul class="pagination pagination-gutter  justify-content-end">
                            
                                <li class="page-item page-indicator ">
                                    <a class="page-link" href="{% if user_list.has_previous %}
                                                                ?page={{ user_list.previous_page_number }}
                                                                {% else %}
                                                                javascript:void(0);
                                                                {% endif %}">
                                        <i class="la la-angle-left"></i></a>
                                </li>

                            {% for i in user_list.paginator.page_range|slice:":3" %}

                                <li class="page-item {% if user_list.number == i %}
                                                    active{% endif %}"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                            
                            {% endfor %}

                            
                            {% if user_list.number > 3 %}
                            <li class="page-item active"><a class="page-link" href="?page={{ user_list.number }}">{{ user_list.number }}</a></li>
                            {% endif %}
                            
                            <li class="page-item page-indicator ">
                                <a class="page-link"  href="{% if user_list.has_next %}
                                                            ?page={{ user_list.next_page_number }}
                                                            {% else %}
                                                            javascript:void(0);
                                                            {% endif %}">
                                    <i class="la la-angle-right"></i></a>
                            </li>
                            <li>

                              

                            </li>
                        </ul>
                       
                    </nav>
                </div>
            </div>
        </div>


{% endblock %}


{% block additional_js %}

<script>


$(document).ready(function(){


$('#delete_multiple_btn').on('click', function () {

    if(confirm("Are you sure you want to delete items? ")){
        var id = [];
       
        $(':checkbox:checked').each(function(i){
            id[i]=$(this).val();
        });

        if(id.length===0){
            alert("Please select items to delete")
        }else{
            console.log(id);
            $.ajax({
                url:"/delete-multiple-user/",
                method:"POST",
                dataType:'json',
                data:{
                    id,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success:function(res){
                    if(res.warning){
                        document.getElementById("message").innerHTML += '<div class="alert alert-warning alert-dismissible alert-alt solid fade show">\
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close">\
                            </button>'+res.warning+'</div>';

                    }
                    if(res.success){

                        for(var i=0; i < id.length; i++){
                            $('tr#'+id[i]+'').css('background-color','#ccc');
                            // $('tr#'+id[i]+'').fadeOut('slow');
                            $('tr#'+id[i]+'').remove(); 


                        }


                        document.getElementById("message").innerHTML += '<div class="alert alert-success alert-dismissible alert-alt solid fade show">\
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="btn-close">\
                            </button>'+res.success+'</div>';



                    }
                    
                }
            })
        }
    }


});


});







    $('.sweet-success-cancel').on('click', function (event) {
           event.preventDefault();
           const url = $(this).attr('href');
   
           Swal.fire({
               title: 'Are you sure?',
               text: "You won't be able to revert this!",
               type: "warning",
               icon: 'question',
               showCancelButton: true,
               confirmButtonText: "Yes, delete it !!",
               confirmButtonText: 'Delete',
               confirmButtonColor: "#DD6B55"
               
           }).then((result) => {
               if (result.value) {
                   window.location.href = url;
               } else if (result.dismiss === Swal.DismissReason.cancel) {
                   event.preventDefault();
               }
           })
       });
   </script>
   
{% endblock %}
